### ISSUE TITLE
Why so empty?

### ISSUE THREAD

**Issue by Dmole** [curiouslearning/ftm-automation#1]
And where is the FTM source?

**Comment by burrage** [comment]
Hi @Dmole !

The main FTM source code is available here:

https://github.com/curiouslearning/Norad-Eduapp4syria

And also here:

https://github.com/Norad-Eduapp4syria/Norad-Eduapp4syria

We'll be working on making this repo more discoverable and developer-friendly at some point in the near future.

May I ask what is interesting you exactly in the FTM source code?

Hope this helps!

**Comment by Dmole** [comment]
Thought it may be fun to expand the game a bit.
make the levels more consistent
add more levels (up to the "the ten hundred words used most often"
